export { inferCategory } from "./capture/infer-category.js";
export { CaptureQueue } from "./capture/queue.js";
export { ContextSweep } from "./capture/sweep.js";
export { loadConfig } from "./config.js";
export type { ConflictResolution } from "./consolidation/adjudicator.js";
export { Adjudicator } from "./consolidation/adjudicator.js";
export { ApprovalInterface } from "./consolidation/approval.js";
export type { ConsolidationProposal } from "./consolidation/consolidation-proposal.js";
export { Proposer } from "./consolidation/proposer.js";
export { Injector } from "./retrieval/injector.js";
export { HybridRetriever } from "./retrieval/retriever.js";
export type { EmbedderConfig } from "./scoring/create-embedder.js";
export { createEmbedder } from "./scoring/create-embedder.js";
export type { Embedder } from "./scoring/embedder.js";
export { HarnessEmbedder, LocalEmbedder } from "./scoring/embedder.js";
export { DEFAULT_WEIGHTS, Scorer } from "./scoring/scorer.js";
export { AuditLog } from "./storage/audit-log.js";
export type { BM25Result, VecResult } from "./storage/index-db.js";
export { IndexDB } from "./storage/index-db.js";
export { VaultReader } from "./storage/vault-reader.js";
export { VaultWriter } from "./storage/vault-writer.js";
